### ISSUE TITLE
157쪽 그림3-42 와 159쪽 그림 3-43이 바뀐거 같습니다.

### ISSUE THREAD

**Issue by g9736ms** [sysnet4admin/_Book_k8sInfra#1]
ingress-config.yaml 과 ingress.yaml 에 대한 설명 그림입니다.
확인 부탁드리겠습니다 :)
감사합니다.

**Comment by sysnet4admin** [comment]
네 말씀해 주신 것과 같이 바뀌어 있습니다. 
출판사 정오표에 올라갈 예정이고, 추후 발간되는 eBook과 2쇄에는 해당 내용이 수정되어 발행될 예정입니다. 
좋은 정보 감사드립니다.
