### ISSUE TITLE
[ 03 / 176 ] powershell 구문에 대한 질문입니다.

### ISSUE THREAD

**Issue by Austin-Kho** [sysnet4admin/_Book_k8sInfra#14]
질문 하나 드려도 될까요? 책 본문에 (예를 들면 P.176 등) pod 에 부하를 만들기 위해서 호스트 powershell 에서 입력하는 아래의 명령 구문에 대해서인데요.

```console
$i=0; while($true)
{
    % { $i++; write-host -NoNewline "$i $_" }
    (Invoke-RestMethod "http://192.168.1.11")-replace '\n', " "
}
```

호스트가 맥이나 리눅스인 경우 터미널을 통해서 위와 동일한 기능을 하는 구문을 알 수 있을까요? 테스트를 해보고 싶은데 실력이 딸려서 구문을 찾기가 어렵네요 ㅠㅠ;

**Comment by sysnet4admin** [comment]
여긴 질문하는 페이지가 아닙니다. 
issue를 열때 template을 확인해주세요.

**Comment by sysnet4admin** [comment]
위와 같은 개인의 이해에 대한 질문은 오픈채팅방이나 쿠버네티스 유저그룹 등에 질문 주셔도 좋을 내용으로 판단되기도 하오니 참고해 주시기 바랍니다. 

쿠버네티스 오픈 채팅: https://open.kakao.com/o/gxSooElb (암호: kubectl)

쿠버네티스 유저 그룹: https://www.facebook.com/groups/k8skr
