### ISSUE TITLE
[ 챕터 2.1.3 / 페이지 42 ] 베이그런트 우분투 설정

### ISSUE THREAD

**Issue by noyeah-man** [sysnet4admin/_Book_k8sInfra#15]
**중요**  이슈를 받기 어려운 사항은 다음과 같습니다. 
1. 개개인의 환경에 영향을 받는 `vagrant` 에러(error)와 관련된 이슈
    하지만 다음의 사항에 모두 해당 한다면 이슈를 부탁드립니다.  
> - [ ]  초기화된(새로 설치) 노트북(또는 PC)
> - [ ]  책에서 제시한 프로그램과 동일한 버전 설치
> - [ ]  할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행
> - [ ]  2대 이상 동일하게  문제가 발생함

2. 책의 `오타` 및 `형식의 오류` 
    이와 같은 경우에는 다음의 절차를 따라서 진행 
> - [ ]  [길벗](https://www.gilbut.co.kr) 홈페이지에 접속 
> - [ ]  고객센터 클릭 
> - [ ]  1:1문의 접속 후에 오류 및 문의 사항을 제보 

위의 사항 외에 기술적인 문의라면 편하게 여기에 남겨주시면 가능한 빨리(평균적으로 1일 이내) 회신드리도록 하겠습니다. 

## [ 내용 ]

안녕하십니까 책을 보고 학습을 하려고 합니다.

베이그런트 클라우드에서 centos가 아닌 ubuntu를  설치해서 사용하고 싶은데 

따로 쿠버네티스 실습에 필요한 설정 변경 사항을 추가 해줘야 하는지 궁금합니다.

**Comment by sysnet4admin** [comment]
현재 페이지는 `issues` 를 위한 페이지입니다.

**Comment by sysnet4admin** [comment]
기존에 올라온 질문에 closed된 질문들을 봐주시면 좋을꺼 같습니다. 
기존에 댓글을 다시 붙여 드립니다. 
===
위와 같은 개인의 이해에 대한 질문은 오픈채팅방이나 쿠버네티스 유저그룹 등에 질문 주셔도 좋을 내용으로 판단되기도 하오니 참고해 주시기 바랍니다.

쿠버네티스 오픈 채팅: https://open.kakao.com/o/gxSooElb (암호: kubectl)

쿠버네티스 유저 그룹: https://www.facebook.com/groups/k8skr

**Comment by sysnet4admin** [comment]
@noyeah-man 
지금 내부적으로 FAQ를 운영하는게 어떤지 대해서 토의중이긴 한데, 
우선 `Ubuntu`는 
https://app.vagrantup.com/sysnet4admin/boxes/Ubuntu-k8s
으로 가능하긴 하나 안되는 부분들은 찾아서 수정하셔야 합니다. 
참고가 되시길 바랍니다.
