### ISSUE TITLE
[ 5.5.1 / P385 ] kubernetes-cd 플러그인 설치 시 azure-commons 플러그인의 버전 호환 문제 발생

### ISSUE THREAD

**Issue by nmin11** [sysnet4admin/_Book_k8sInfra#21]
**중요**  이슈를 받기 어려운 사항은 다음과 같습니다. 

1. 책에 사용되는 환경 및 기술과 관련된 `질문` </br>
   또는 책에서 구성한 `환경외` 조건에서 발생한 이슈
   > `goto` 
   > 1. 쿠버네티스 오픈 채팅: https://open.kakao.com/o/gxSooElb (암호: kubectl)
   > 2. 쿠버네티스 유저 그룹: https://www.facebook.com/groups/k8skr
   
2. 개개인의 환경에 영향을 받는 `vagrant` 에러(error)와 관련된 이슈 </br>
   하지만 다음의 사항에 모두 해당 한다면 이슈를 부탁드립니다.  
   > - [ ]  초기화된(새로 설치) 노트북(또는 PC)
   > - [ ]  책에서 제시한 프로그램과 동일한 버전 설치
   > - [ ]  할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행
   > - [ ]  2대 이상 동일하게  문제가 발생함

3. 책의 `오타` 및 `형식의 오류` 
    이와 같은 경우에는 다음의 절차를 따라서 진행 
   > - [ ]  [길벗](https://www.gilbut.co.kr) 홈페이지에 접속 
   > - [ ]  고객센터 클릭 
   > - [ ]  1:1문의 접속 후에 오류 및 문의 사항을 제보 

위의 사항 외에 `이슈`라면 가능한 빨리(평균적으로 1일 이내) 회신드리도록 하겠습니다. 

## [ 내용 ]

385 페이지 - **Kubernetes Continuous Deploy** 플러그인 설치 후 젠킨스를 재시작해서 **Jenkins 관리** 탭에 갔을 때
![azure commons 호환 문제](https://user-images.githubusercontent.com/75058239/163707914-0cf13e94-a29e-4992-9247-ce7cdc071a33.png)

```
Some plugins could not be loaded due to unsatisfied dependencies. Fix these issues and restart Jenkins to re-enable these plugins.

Dependency errors:

Azure Commons Plugin (1.1.3)
  Jenkins (2.266) or higher required

Some of the above failures also result in additional indirectly dependent plugins not being able to load.

Indirectly dependent plugins:

Kubernetes Continuous Deploy Plugin (2.3.1)
  Failed to load: Azure Commons Plugin (1.1.3)
```

**Azure Commons Plugin** 이 젠킨스 버전 호환 문제로 적용되지 않아 kubernetes-cd도 작동하지 않습니다. 
혹시나 해서 앞선 임시 해결책과 같이 버전 다운그레이드가 될까 싶어서 확인해봤지만 아래와 같이 활성화된 버튼이 없었습니다.
![kubernetes cd 플러그인](https://user-images.githubusercontent.com/75058239/163708139-80b1fa04-5351-4418-8e51-fd9c6b28d716.png)

확인 한번만 부탁드립니다!

**Comment by sysnet4admin** [comment]
## 문제 확인 
해당 내용을 확인하였습니다.  
![image](https://user-images.githubusercontent.com/29163931/163709995-d2270195-0369-4773-bc75-be4074a5dfc9.png)

</br>

## 문제 세부 내용 
이 부분은 현재 젠킨스에서 받아오는 **update-center.json**의 "requiredCore" 정보가 `2.266`으로 되어 있습니다. 하지만, 여러가지의 변동 사항을 주지 않으며 원할한 실습을 위해서 현재 젠킨스 버전은 `2.249.3`으로 고정되어 있습니다. 그리고 책의 모든 내용은 테스트되어진 데이터로 구성되어 있기 때문에 "requiredCore"도 젠킨스 보다 보다 낮은 버전(2.249.3)이 제공되고 있었을 것입니다

</br>

## 구체적인 해결 방법  
시간이 흐르고 흘러....
일부 requiredCore 정보 및 플러그인 의존성 정보들이 업데이트 되면서 문제(#20)가 야기되고 있는 것을 영구적으로 해결하기 위해서 [**update-center.json**](https://raw.githubusercontent.com/IaC-Source/Jenkins-updateCenter/main/update-center.json)을 직접 제공하도록 코드를 변경하였습니다. 
해당 **update-center.json**에서는 azure-common을 위한 "requiredCore"를  `2.138.4`로 정의하고 있기 때문에 문제가 없을 것입니다. 

</br>

## 정리 
정리하자면...
azure-common의 "requiredCore" 버전이 업데이트 되면서 현재 젠킨스 버전보다 높은 `2.266` 버전을 요구함
그래서 플러그인이 설치되지 못한 것입니다.  

</br>

## 현재 필요한 조치 내용 
[**update-center.json**](https://raw.githubusercontent.com/IaC-Source/Jenkins-updateCenter/main/update-center.json) 은 젠킨스가 설치되는 시점에 [jenkins-config.yaml](https://github.com/sysnet4admin/_Book_k8sInfra/blob/main/ch5/5.3.1/jenkins-config.yaml)을 호출해 오도록 설계되어 있습니다. 
따라서 다음과 같이 실행하시어 젠킨스를 다시 설치하고 실습하시기 바랍니다. 

1. helm uninstall jenkins 
2. rm -rf /nfs_shared/jenkins/*
3. ~/_Book_k8sInfra/ch5/5.3.1/jenkins-install.sh

</br>

## 다시 설치 후에 실습되는 것 확인 
![image](https://user-images.githubusercontent.com/29163931/163710903-33829002-cbdb-46ef-9a9d-018b930fad0c.png)


## 관련된 사항들
[update-center.json(Apr-17-2022)](https://gist.githubusercontent.com/gnu-gnu/436b38519181c3d3caa778d8331193a6/raw/03185a6423cfe345a455b0bff29c83befa6adc0b/gistfile1.txt)
[update-center.json(쿠버네티스 책을 위해 고정)](https://raw.githubusercontent.com/IaC-Source/Jenkins-updateCenter/main/update-center.json)


해당 이슈는 1주일간 모니터링 된 후에 ```Close``` 됩니다. 
감사합니다. 
[조 훈](https://github.com/sysnet4admin), [심근우](https://github.com/gnu-gnu), [문성주](https://github.com/seongjumoon) 드림

**Comment by nmin11** [comment]
![gitops 배포 성공](https://user-images.githubusercontent.com/75058239/163713804-2310938e-00b8-4adc-b182-275528a91caf.png)
젠킨스 재설치 이후 플러그인들 다시 설치하고 gitops 배포까지 성공했습니다!
이번 기회에 환경 세팅 관련해서도 많이 배웠습니다. 감사합니다.
