### ISSUE TITLE
[ 3.3.1 / P 147 ] nodeport 설명과정에서 생성하는 deployment 생성에 대해 질문이 있습니다..

### ISSUE THREAD

**Issue by TerryChang** [sysnet4admin/_Book_k8sInfra#22]
**중요**  이슈를 받기 어려운 사항은 다음과 같습니다. 

1. 책에 사용되는 환경 및 기술과 관련된 `질문` </br>
   또는 책에서 구성한 `환경외` 조건에서 발생한 이슈
   > `goto` 
   > 1. 쿠버네티스 오픈 채팅: https://open.kakao.com/o/gxSooElb (암호: kubectl)
   > 2. 쿠버네티스 유저 그룹: https://www.facebook.com/groups/k8skr
   
2. 개개인의 환경에 영향을 받는 `vagrant` 에러(error)와 관련된 이슈 </br>
   하지만 다음의 사항에 모두 해당 한다면 이슈를 부탁드립니다.  
   > - [ ]  초기화된(새로 설치) 노트북(또는 PC)
   > - [ ]  책에서 제시한 프로그램과 동일한 버전 설치
   > - [ ]  할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행
   > - [ ]  2대 이상 동일하게  문제가 발생함

3. 책의 `오타` 및 `형식의 오류` 
    이와 같은 경우에는 다음의 절차를 따라서 진행 
   > - [ ]  [길벗](https://www.gilbut.co.kr) 홈페이지에 접속 
   > - [ ]  고객센터 클릭 
   > - [ ]  1:1문의 접속 후에 오류 및 문의 사항을 제보 

위의 사항 외에 `이슈`라면 가능한 빨리(평균적으로 1일 이내) 회신드리도록 하겠습니다. 

## [ 내용 ]
안녕하세요..먼저 좋은 내용의 책을 써주셔서 고맙다는 인사를 드리며 질문 좀 드려보겠습니다..
다름이 아니라 3.3 쿠버네티스 연결을 담당하는 서비스 의 147 페이지에 보면 노드포트를 설명하는 과정에서 다음과 같이 deployment 를 만들어주고 있는데요

kubectl create deployment np-pods --image=sysnet4admin/echo-hname

그런데 제가 질문 드리고 싶은 내용은 이렇게 생성하게 될 경우 echo-hname 이미지를 이용한 Pod 의 컨테이너 생성과정에서 포트가 열리지 않고 Pod 이 생성되기 때문에 그 후에 만들어지는 서비스와 연결이 이루어지지 않는 걸로 알고 있습니다..
그래서 이걸 제대로 할려면

kubectl create deployment np-pods --image=sysnet4admin/echo-hname --port=80

이렇게 --port 옵션을 주어서 80 포트를 열어주라고 해야 해당 이미지로 생성된 컨테이너의 80 포트가 열려져서 통신이 가능한 걸로 알고 있거든요..

실제로 --port 옵션을 빼고 진행하면 웹브라우저 테스트 단계에서 응답이 없다고 나옵니다..

제가 이 부분이 길벗출판사의 책 설명 페이지의 정오표에 반영되어있는지 확인해봤는데 길벗출판사의 책 설명 페이지에서 정오표를 찾지 못해서 이슈로 등록하는 형태로 질문을 드려보았습니다..

확인 부탁드립니다..
고맙습니다..

**Comment by sysnet4admin** [comment]
안녕하세요 
issue tab은 질문을 하기 위한 목적으로 사용되지 않습니다. 
참고로 
지금 의도하시는건 `create`가 아니라 `expose` 부분인거 같습니다. 
또한 컨테이너 포트는 `4장`을 보시는게 좋으실꺼 같습니다.
