### ISSUE TITLE
[5.3.3 / p322] 젠킨스 plugin 인증서 이슈 

### ISSUE THREAD

**Issue by sysnet4admin** [sysnet4admin/_Book_k8sInfra#23]
### 문제 

**에러 로그**
`
Update information obtained: 8.1 sec ago 
There were errors checking the update sites: Signature verification failed in update site &#039;default&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertificateExpiredException: NotAfter: Tue Jun 14 19:42:00 KST 2022<br> at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)<br> at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:677)<br> at sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)<br> at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)<br> at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)<br>Caused: java.security.cert.CertPathValidatorException: validity check failed<br> at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)<br> at 
`

**에러 화면**
![image](https://user-images.githubusercontent.com/29163931/177733899-c48b93df-25e9-46d1-91c7-0228c951746f.png)

### 상태
**문제 확인 중**

**Comment by sysnet4admin** [comment]
### 문제 원인
`update-center.json`을 와 으로 고정했던 것이 원인이었습니다. 

**update-center.json의 인증서 부분 일부**
`
80389     "signature": {
80390         "certificates": ["MIIFYTCCA0kCBQDerb78MA0GCSqGSIb3DQEBDQUAMIGKMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTERM      A8GA1UEBwwIU2FuIEpvc2UxGDAWBgNVBAoMD0plbmtpbnMgUHJvamVjdDEaMBgGA1UEAwwRS29oc3VrZSBLYXdhZ3VjaGkxHTAbBgkqhkiG9w0BCQEWDmtr      <snipped>
`

이에 해당 certifications(인증/인증서)를 고정하지 않고 동적으로 동작하도록 코드를 변경하였습니다. 
**jenkins-install.sh** 변경 
```
   1   │ #!/usr/bin/env bash
   2   │ jkopt1="--sessionTimeout=1440"
   3   │ jkopt2="--sessionEviction=86400"
   4   │ jvopt1="-Duser.timezone=Asia/Seoul"
   5   │ jvopt2="-Dcasc.jenkins.config=https://raw.githubusercontent.com/sysnet4admin/_Book_k8sInfra/main/ch5/5.3.1/jenkins-config.yaml
       │ "
   6 + │ jvopt3="-Dhudson.model.DownloadService.noSignatureCheck=true".  <<< 추가
   7   │
   8   │ helm install jenkins edu/jenkins \
   9   │ --set persistence.existingClaim=jenkins \
  10   │ --set master.adminPassword=admin \
  11   │ --set master.nodeSelector."kubernetes\.io/hostname"=m-k8s \
  12   │ --set master.tolerations[0].key=node-role.kubernetes.io/master \
  13   │ --set master.tolerations[0].effect=NoSchedule \
  14   │ --set master.tolerations[0].operator=Exists \
  15   │ --set master.runAsUser=1000 \
  16   │ --set master.runAsGroup=1000 \
  17   │ --set master.tag=2.249.3-lts-centos7 \
  18   │ --set master.serviceType=LoadBalancer \
  19   │ --set master.servicePort=80 \
  20   │ --set master.jenkinsOpts="$jkopt1 $jkopt2" \
  21 ~ │ --set master.javaOpts="$jvopt1 $jvopt2 $jvopt3"    <<< $jvoopt3 추가 
```

### 문제 해결 확인

**배포된 jenkins 삭제** 
```
[root@m-k8s 5.3.1]# helm uninstall jenkins 
release "jenkins" uninstalled
```
 **소스 코드 업데이트 이후!!! 다시 jenkins 배포**
```
[root@m-k8s 5.3.1]# ./jenkins-install.sh 
NAME: jenkins
LAST DEPLOYED: Fri Jul  8 06:36:00 2022
NAMESPACE: default
STATUS: deployed
<snipped> 
```

**업데이트 이후 배포된 jenkins**
![image](https://user-images.githubusercontent.com/29163931/177876558-13871d27-5386-48b7-b661-d9670946f30e.png)

![image](https://user-images.githubusercontent.com/29163931/177876634-7b7ccd7e-2c0f-41cc-9c77-64e918d2bbc3.png)


현재 이슈는 1주일간 모니터링 된 후에 Close 됩니다.
감사합니다.
[조 훈](https://github.com/sysnet4admin), [심근우](https://github.com/gnu-gnu), [문성주](https://github.com/seongjumoon) 드림

**Comment by jys94** [comment]
혹시 컨테이너 인프라 환경 구축을 위한 쿠버네티스/도커 책에서 소개해주신 젠킨스, 프로메테우스, 그라파나를 헬름으로 다운받을 때 AWS EKS에 적용하기란 쉽지 않을까요? 프로젝트라서 젠킨스랑 모니터링 넣으려고 하는데 제공해주는 헬름 리포지토리가 온프레미스 초점맞춰서 가공된 것들이라면 EKS에서 설치하는 방법은 따로 알아봐야 하나요? ㅠ

**Comment by aeroshim** [comment]
[ 5.3.1 / Page 306 ] jenkins-install.sh 
이것을 여러번 했는데도 무한루프 현상이 발생하네요,,  
- 노트북 디스크가 계속 돌아갑니다(2일 이상)
- kubectl 같은 명령이 안먹히네요 

o 왜 이런현상이 나타나는지 조회하는 방법이 있을까요 ?

**Comment by aeroshim** [comment]
# 노트북 무한루프 현상은 해결됨(vm 메모리 용량문제)

# kubectl get service

NAME            TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)        AGE
jenkins         LoadBalancer   10.105.230.209   192.168.56.11   80:32317/TCP   11m
jenkins-agent   ClusterIP      10.105.246.137   <none>          50000/TCP      11m
kubernetes      ClusterIP      10.96.0.1        <none>          443/TCP        37h

# ps -ef |grep jenkins

[root@m-k8s nfs_shared]# ps -ef |grep jenkins
vagrant  15791 15774  0 01:01 ?        00:00:00 /sbin/tini -- /usr/local/bin/jenkins.sh --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin --httpPort=8080
vagrant  15812 15791  4 01:01 ?        00:00:32 java -Duser.home=/var/jenkins_home -Duser.timezone=Asia/Seoul -Dcasc.jenkins.config=https://raw.githubusercontent.com/aeroshim/_Book_k8sInfra/main/ch5/5.3.1/jenkins-config.yaml -Dhudson.model.DownloadService.noSignatureCheck=true -Dcasc.reload.token=jenkins-8bdc9fdcb-jssrt -Djenkins.model.Jenkins.slaveAgentPort=50000 -jar /usr/share/jenkins/jenkins.war --sessionTimeout=1440 --sessionEviction=86400 --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin --httpPort=8080
vagrant  17069 15812  0 01:01 ?        00:00:00 [jenkins.sh] <defunct>
root     31980  2152  0 01:13 pts/0    00:00:00 grep --color=auto jenkins



# service 는 80 
# ps -ef 하면 8080으로 나오는데

잘못된것 아닌가요 이해할수가 없네요? 뭐가 문제인지 ?
