### ISSUE TITLE
[ 5.2.3 / 302 ] Helm으로 설치한 LoadBalancer <pending> 오류 해결 공유

### ISSUE THREAD

**Issue by stae1102** [sysnet4admin/_Book_k8sInfra#27]
## 개인적인 문제일지 잘 모르겠으나, 저와 같은 문제를 겪고 계신 분들께 도움이 될까 하여 공유하고 싶습니다.

# 문제 : Helm repo를 등록하고 metallb를 설치한 이후로도 deployment의 external-ip가 할당되지 않는 오류
![image](https://user-images.githubusercontent.com/83271772/191240636-378975b4-2deb-4a88-bd87-022701e79e2b.png)

이에 대하여 헬름으로 설치된 것을 확인하였는데 확인되지 않음
![image](https://user-images.githubusercontent.com/83271772/191240796-c1a64c64-ff7b-479f-944b-d8e4c15de7a8.png)

그래서 다시 install 하려고 해도 설치가 불가
![image](https://user-images.githubusercontent.com/83271772/191240965-5f76bf58-a44a-4782-8d5b-1f323ed88ec5.png)

그래서 구글링 하면서 삭제 방법을 찾아서 직접 삭제했습니다.

### 1. metallb-system 네임스페이스의 secret을 조회합니다.
![image](https://user-images.githubusercontent.com/83271772/191241267-e450c59f-2b94-4bc2-9021-a045dcac9673.png)
### 2. 해당 정보를 바탕으로 secret을 삭제합니다.
![image](https://user-images.githubusercontent.com/83271772/191241764-84dfe9e8-318a-4bb9-abea-d11913239a03.png)
### 3. 교재 내용대로 설치해줍니다.
![image](https://user-images.githubusercontent.com/83271772/191241848-da4339c1-9c34-4fd1-9585-091d52f3b413.png)

## 해결 후

![image](https://user-images.githubusercontent.com/83271772/191241957-f6b7219c-f6ea-41be-a657-7aa29a6a07f5.png)

저는 위 방법으로 재설치하고 정상적으로 클러스터에 접근할 수 있었습니다!
혹시 다른 분들께 도움이 될까 공유합니다 :)
좋은 교재 만들어주셔서 감사합니다~

**Comment by sysnet4admin** [comment]
안녕하세요 
좋은 정보 감사드립니다. 

몇가지 수정 드리고 싶은데... 
일단 원인을 현재 알 수 없는거 같으니 그 부분은 skip하면 될 것 같긴 한데...

helm에도 `namespace`라는 요소가 있어서요..
jenkins, prometheus, grafana는 `default` namespace에 설치되었으나..
metallb는 잘 아시는 `metallb-system`에 설치되어 있습니다. 

따라서 다음과 같이 `-n metallb-system`을 추가하여 **ls** 또는 **uninstall** 하셔야 합니다. 

```
[root@m-k8s ~]# helm ls -n metallb-system 
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
metallb metallb-system  1               2022-07-07 17:31:19.223415107 +0900 KST deployed        metallb-0.1.1   0.8.2      
```

참고하시면 좋으실 것 같습니다. 
조훈 드림.

**Comment by sysnet4admin** [comment]
그러면 해당 issue는 close 하도록 하겠습니다. 감사합니다.

**Comment by stae1102** [comment]
감사합니다!!
