### ISSUE TITLE
[ 챕터 위치 / 페이지 ] 이슈 제목

### ISSUE THREAD

**Issue by yoondonggyu** [sysnet4admin/_Book_k8sInfra#31]
교재로 공부를 진행하던 중 젠킨스 빌드가 안되는 오류가 발생하였는데 뭐가 문제인가요?
도커가 없다는 오류 같아서 확인해보니 도커는 있습니다.

교재 p344 페이지입니다.

Started by user admin
Running as SYSTEM
Agent default-qb8pr is provisioned from template default
---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/label-digest: "6ba93233d22ff0212c5c877dbc5afb06b7d3aafc"
    jenkins/jenkins-jenkins-slave: "true"
    jenkins/label: "jenkins-jenkins-slavex"
  name: "default-qb8pr"
spec:
  containers:
  - args:
    - "********"
    - "default-qb8pr"
    env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_TUNNEL"
      value: "jenkins-agent:50000"
    - name: "JENKINS_AGENT_NAME"
      value: "default-qb8pr"
    - name: "JENKINS_NAME"
      value: "default-qb8pr"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins"
    - name: "JENKINS_URL"
      value: "http://192.168.1.11"
    image: "jenkins/inbound-agent:4.3-4"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    resources:
      limits:
        memory: "512Mi"
        cpu: "512m"
      requests:
        memory: "512Mi"
        cpu: "512m"
    tty: false
    volumeMounts:
    - mountPath: "/usr/bin/kubectl"
      name: "volume-0"
      readOnly: false
    - mountPath: "/bin/docker"
      name: "volume-1"
      readOnly: false
    - mountPath: "/var/run/docker.sock"
      name: "volume-2"
      readOnly: false
    - mountPath: "/home/jenkins"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins"
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  securityContext:
    runAsGroup: 993
    runAsUser: 1000
  serviceAccount: "jenkins"
  volumes:
  - hostPath:
      path: "/usr/bin/kubectl"
    name: "volume-0"
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-2"
  - hostPath:
      path: "/bin/docker"
    name: "volume-1"
  - emptyDir:
      medium: ""
    name: "workspace-volume"

Building remotely on default-qb8pr (jenkins-jenkins-slave) in workspace /home/jenkins/workspace/dpy-fs-dir-prod
The recommended git tool is: NONE
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/iac-source/echo-ip
 > git init /home/jenkins/workspace/dpy-fs-dir-prod # timeout=10
Fetching upstream changes from https://github.com/iac-source/echo-ip
 > git --version # timeout=10
 > git --version # 'git version 2.20.1'
 > git fetch --tags --force --progress -- https://github.com/iac-source/echo-ip +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/iac-source/echo-ip # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision 5ed2bf9132d6fabf9481ea8f90b1bdddd74490fe (refs/remotes/origin/main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 5ed2bf9132d6fabf9481ea8f90b1bdddd74490fe # timeout=10
Commit message: "Update README.md"
First time build. Skipping changelog.
[dpy-fs-dir-prod] $ /bin/sh -xe /tmp/jenkins2525911456150578809.sh
+ docker build -t 192.168.1.10:8443/echo-ip .
/bin/docker: 2: .: Can't open /etc/sysconfig/docker
Build step 'Execute shell' marked build as failure
Finished: FAILURE

![image](https://github.com/sysnet4admin/_Book_k8sInfra/assets/94845888/7e8831de-e161-427b-aa68-7fb4df00bf26)

**Comment by yoondonggyu** [comment]
혹시 제가 공부 중에 챕터 5에서 가상환경을 모두 지우고 재설치해서 진행하였는데 이게 도커 파일이 없다고 나오는 오류와 연관이 있을까요?

**Comment by sysnet4admin** [comment]
책에 관련해서는 개개인의 질문 답변은 어렵습니다. 
(아시는 것처럼 개인의 여러가지 호스트 시스템 문제, 실수, 다른 종류의 이슈등) 
책이 잘못 구성된 것에 대해서만 가능합니다. 
양해 부탁드립니다.

**Comment by sysnet4admin** [comment]
해당 이슈는 종료됩니다.
