### ISSUE TITLE
[ 3.1.3 ] pod create 불가한 문제

### ISSUE THREAD

**Issue by zenio7** [sysnet4admin/_Book_k8sInfra#33]
> - [ ]  초기화된(새로 설치) 노트북(또는 PC)
   > - [ ]  책에서 제시한 프로그램과 동일한 버전 설치
   > - [ ]  할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행 ~ 자택에서 수행함
   > - [ ]  2대 이상 동일하게  문제가 발생함 ~ 2대이상에서 테스트해보지 못했습니다. 

## [ 내용 ]

파트 3.1.3 의 nginx-pod.yaml 을 kubectl create 명령실행했을때 
kubectl get pod의 상태가 ErrImage 이후 ImagePullBackoff 과정이 반복됩니다.

혹시나하여 docker pull nginx 해보니 missing signature key 에러발생하고요. 

vagrant up 했을때 로그중에 
 w1-k8s: SSH username: vagrant
    w1-k8s: SSH auth method: private key
    w1-k8s: Warning: Connection reset. Retrying...
    w1-k8s: Warning: Connection aborted. Retrying...
    w1-k8s: Warning: Connection reset. Retrying...
    w1-k8s: Warning: Connection aborted. Retrying...
    w1-k8s: Warning: Connection reset. Retrying...
    w1-k8s: Warning: Connection aborted. Retrying...
    w1-k8s: 
    w1-k8s: Vagrant insecure key detected. Vagrant will automatically replace
    w1-k8s: this with a newly generated keypair for better security.
    w1-k8s: 
    w1-k8s: Inserting generated public key within guest...
    w1-k8s: Removing insecure key from the guest if it's present...
    w1-k8s: Key inserted! Disconnecting and reconnecting using new SSH key...
==> w1-k8s: Machine booted and ready!

이런 내용이찍히던데 해당로그와 관련이 있는건지
윈도우11 포맷하고 해보아도 같은증상이네요.

**Comment by sysnet4admin** [comment]
안녕하세요 
문제가 확실히 정의 되었을 때 질문이 주시는 것을 부득이하게 요청드립니다. 
```
 (X) 2대 이상 동일하게 문제가 발생함 ~ 2대이상에서 테스트해보지 못했습니다.
 ```
책을 집필한 이후 문제가 생기는 것을 follow up하기 위해 현재 issues 페이지는 운영되고 있습니다. 
현재 발생하신 이슈가 정확하게 정의되지 않으면 답변하기 어려울 뿐만 아니라 제가 재현할 수 없는 부분에 대해서도 해결을 해드리기가 어렵습니다. 

우선 3.1.3에는 nginx-pod.yaml이 존재하지 않고
3.1.6에 존재하는 nginx-pod.yaml을 배포하면 정상적으로 동작합니다. 
```
[root@m-k8s ch3]# cd 3.1.6 
[root@m-k8s 3.1.6]# ls -rlt 
total 4
-rw-r--r--. 1 root root 115 Nov 15 09:42 nginx-pod.yaml
[root@m-k8s 3.1.6]# k apply -f nginx-pod.yaml 
pod/nginx-pod created
[root@m-k8s 3.1.6]# k get po -o wide 
NAME                          READY   STATUS    RESTARTS   AGE   IP               NODE     NOMINATED NODE   READINESS GATES
fs-echo-ip-5db6b4d665-7ghpv   1/1     Running   1          56d   172.16.103.130   w2-k8s   <none>           <none>
jenkins-76496d9db7-2f6rx      2/2     Running   2          56d   172.16.171.69    m-k8s    <none>           <none>
nginx-pod                     1/1     Running   0          24s   172.16.132.2     w3-k8s   <none>           <none>
```
해당 문제는 현재 사용하시는 호스트 및 환경에 어떤 제약(Network등) 또는 문제에서 기인하는 것으로 보입니다.

**Comment by sysnet4admin** [comment]
### 문제
현재 책에서 사용하고 있는 docker-ce(v18.09)에서는 문제가 발생하지 않으나, ch3의 docker(v1.13.1)에서는 문제가 재현 됨을 확인했습니다.
문제의 원인은 Docker의 'missing signature key' 이며, 
```
Warning  Failed     2s (x2 over 19s)  kubelet, w2-k8s    Failed to pull image "nginx": rpc error: code = Unknown desc = missing signature key
```
upgrade하면 해결되긴 하나...이렇게 하는 경우 ch4로 넘어갈 때 연결성에 문제가 있어서
해결 방법에 대해서 고민 중에 있습니다. 
우선 

### 임시 해결 방법
`ch4/4.3.4/k8s-SingleMaster-18.9_9_w_auto-compl` 에 있는 Vagrantfile+연결파일 들로 진행하시면 해당 문제는 발생하지 않습니다. 

조치 방법이 결정되면 다시 공지 드리도록 하겠습니다. 
사용에 불편을 끼쳐드려서 죄송합니다.

**Comment by ksnd0297** [comment]
저도 동일한 이슈를 겪고 있습니다. 1.13.1 에서 왜 missing signature key 에러가 발생하는지도 알려주시면 감사하겠습니다.

**Comment by sysnet4admin** [comment]
### 문제 원인 
도커 1.13.1 버전에서 OCI(Open Container initiative) 형식이 다른(v2) 컨테이너 이미지에 대해서 pulling이 되지 않음. 
이 경우에 출력되는 메시지가 `missing signature key` 인 이유는 도커 1.13.1 버전에서 식별해야하는 매니페스트(MediaType) 형식과 nginx:latest(현재 1.25.3)의 매니페스트(MediaType)이 달라 해당 [에러](https://github.com/moby/moby/blob/092cba3727bb9b4a2f0e922cd6c0f93ea270e363/vendor/github.com/docker/libtrust/jsonsign.go#L25)에 해당하는 코드가 반환되면서 컨테이너 이미지 pull 되지 않게 되었습니다. 
문제의 세부 원인은 가장 하단을 참고 하시기 바랍니다. 
</br>

### 해결 방법 
[ch3/3.1.3](https://github.com/sysnet4admin/_Book_k8sInfra/tree/main/ch3/3.1.3)에 있는 Vagrantfile을 이용해서 다시 vagrant up 진행 
`또는` 
[새로 업로드된 가상 머신(VM) 이미지](https://onedrive.live.com/?authkey=%21ABYJfjk7c25L58Y&id=F9728AC19FDDBFEB%21119&cid=F9728AC19FDDBFEB)를 이용해서 실습을 진행 
</br>

### 영향 받는 페이지 
**P89:** `config.sh` 끝 부분에 docker-ce를 받기 위한 docker repo가 추가됨 
**P149:** `kubectl get nodes -o wide`의 결괏값 중에 CONTAINER-RUNTIME이 바뀜 
**P255:** 현재 사용하는 도커 버전이 18.6.0이라고 기입되어야 하고, 끝 부분에 CONTAINER-RUNTIME이 변경됨 
</br>

### 변경 후 확인 
#### 노드 상태 확인 
```bash 
[root@m-k8s ~]# kubectl get nodes
NAME     STATUS   ROLES    AGE     VERSION
m-k8s    Ready    master   13m     v1.18.4
w1-k8s   Ready    <none>   9m27s   v1.18.4
w2-k8s   Ready    <none>   5m39s   v1.18.4
w3-k8s   Ready    <none>   115s    v1.18.4
```
#### 디플로이먼트 배포 테스트
``` bash 
[root@m-k8s ~]# kubectl create deployment nginx --image=nginx 
deployment.apps/nginx created
[root@m-k8s ~]# kubectl scale deployment nginx --replicas 6
deployment.apps/nginx scaled
[root@m-k8s ~]# kubectl get pods -o wide 
NAME                    READY   STATUS    RESTARTS   AGE     IP               NODE     NOMINATED NODE   READINESS GATES
nginx-f89759699-6m9fw   1/1     Running   0          108s    172.16.221.130   w1-k8s   <none>           <none>
nginx-f89759699-9htz5   1/1     Running   0          108s    172.16.221.129   w1-k8s   <none>           <none>
nginx-f89759699-b4mwr   1/1     Running   0          108s    172.16.132.2     w3-k8s   <none>           <none>
nginx-f89759699-b8jhs   1/1     Running   0          108s    172.16.103.130   w2-k8s   <none>           <none>
nginx-f89759699-g5rzw   1/1     Running   0          108s    172.16.103.129   w2-k8s   <none>           <none>
nginx-f89759699-tb9gm   1/1     Running   0          2m25s   172.16.132.1     w3-k8s   <none>           <none>
```
</br>

### 문제 세부 원인 
컨테이너 이미지는 보통 다음 4가지로 구성되어 있습니다. [[참고 자료](https://shortstories.gitbook.io/studybook/container/image)]
- image index
- manifest
- config
- layer

이때 내려받은 최신(latest) nginx의 해석을 위해서 manifest에 있는 mediatype을 해석해야 하는데...
1.13.1 도커 버전에서 mediatype을 정상적으로 인지하기 위해서는 mediatype을 `application/vnd.docker.distribution.manifest.v1+json` 으로 제공되어야 하나 [최신 nginx 이미지](https://explore.ggcr.dev/?image=nginx:latest)는 'application/vnd.docker.distribution.manifest.v2+json' 으로만 제공되는 것으로 보입니다. 
이에 반해 예를 들면 최신 nginx 이미지가 아닌 [1.18](https://explore.ggcr.dev/?image=nginx:1.18)의 경우에는 `application/vnd.docker.distribution.manifest.v1+json` 형태로 제공됩니다. 

[OCI ](https://github.com/opencontainers/image-spec/blob/main/manifest.md) 에서 [호환](https://github.com/opencontainers/image-spec/blob/main/media-types.md#compatibility-matrix)을 위해서 `application/vnd.docker.distribution.manifest.v1+json` 이 가능하도록 권장하기 하긴 하나, 이는 강제할 수 있는 사항이 아니기 때문에 **v2**가 가능한 도커 버전을 적용해야 했고, 테스트 결과 가장 변경 점이 적은 버전은 **1.18.6**으로 확인되었습니다. 

따라서 [ch3/3.1.3](https://github.com/sysnet4admin/_Book_k8sInfra/tree/main/ch3/3.1.3)에 도커 버전을 `1.13.1` 에서 `1.18.6`으로 변경해서 해당 문제를 조치하였습니다. 

nginx 최신(latest) 과 1.18을 비교하고 싶으시다면 [다음](https://www.diffchecker.com/pb8dXNTP/)을 클릭해서 확인해 보실 수 있습니다. 

현재 이슈는 1주일간 모니터링 된 후에 Close 됩니다.
감사합니다.
[조 훈](https://github.com/sysnet4admin), [심근우](https://github.com/gnu-gnu), [문성주](https://github.com/seongjumoon) 드림
