### ISSUE TITLE
[ 챕터5.3.1 / pg318 ] kubectl apply -f jenkins-volume.yaml 실행시 forbidden error

### ISSUE THREAD

**Issue by leesanghwan0131** [sysnet4admin/_Book_k8sInfra#34]
안녕하세요

챕터 5.3.1 젠킨스 설치를 위한 PVC구성중 다음과 같은 error가 발생하였습니다. 

[root@m-k8s 5.3.1]# kubectl apply -f ~/_Book_k8sInfra/ch5/5.3.1/jenkins-volume.yaml
persistentvolume/jenkins unchanged
Error from server (Forbidden): error when creating "/root/_Book_k8sInfra/ch5/5.3.1/jenkins-volume.yaml": persistentvolumeclaims "jenkins" is forbidden: exceeded quota: storagequota, requested: requests.storage=10Gi, used: requests.storage=10Mi, limited: requests.storage=25Mi

[root@m-k8s 5.3.1]# kubectl get pv jenkins
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS   REASON   AGE
jenkins   10Gi       RWX            Retain           Available                                   11h

[root@m-k8s 5.3.1]# kubectl get pvc jenkins
Error from server (NotFound): persistentvolumeclaims "jenkins" not found

[root@m-k8s 5.3.1]# ls -n /nfs_shared/
total 0
drwxrwxrwx. 2 1000 1000 6 Jan 24 23:51 jenkins

[root@m-k8s 5.3.1]# docker version
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.11.13
 Git commit:        039a7df9ba
 Built:             Wed Sep  4 16:51:21 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.13
  Git commit:       039a7df
  Built:            Wed Sep  4 16:22:32 2019
  OS/Arch:          linux/amd64
  Experimental:     false

감사합니다.

**Comment by sysnet4admin** [comment]
안녕하세요
현재 issue 페이지는 `에러`를 올리는 목적으로 사용되지 않습니다. 템플릿에 맞게 기입을 부탁드립니다.

**Comment by leesanghwan0131** [comment]
안녕하세요, 그럼 이와같은 문제는 카카오 오픈챗 그룹에서 여쭤보면 도움을 얻을수 있을까요? 감사합니다.

**Comment by sysnet4admin** [comment]
@leesanghwan0131  템플릿에도 기입되어 있고, 그 부분을 여기서 답변하는 것은 적절하지 않은 것 같습니다.

**Comment by leesanghwan0131** [comment]
storageauota부분이 설정되어 있었군요, 자체적으로 문제를 해결하였습니다.
