### ISSUE TITLE
[ 3장 / 93p ] eos로 인해 yum 설치 오류 문의

### ISSUE THREAD

**Issue by kimms1958** [sysnet4admin/_Book_k8sInfra#37]
**중요**  이슈를 받기 어려운 사항은 다음과 같습니다. 

1. 책에 사용되는 환경 및 기술과 관련된 `질문` </br>
   또는 책에서 구성한 `환경외` 조건에서 발생한 이슈
   > `goto` 
   > 1. 쿠버네티스 오픈 채팅: https://open.kakao.com/o/gxSooElb (암호: kubectl)
   > 2. 쿠버네티스 유저 그룹: https://www.facebook.com/groups/k8skr
   
2. 개개인의 환경에 영향을 받는 `vagrant` 에러(error)와 관련된 이슈 </br>
   하지만 다음의 사항에 모두 해당 한다면 이슈를 부탁드립니다.  
   > - [ ]  초기화된(새로 설치) 노트북(또는 PC)
   > - [ ]  책에서 제시한 프로그램과 동일한 버전 설치
   > - [ ]  할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행
   > - [ ]  2대 이상 동일하게  문제가 발생함

3. 책의 `오타` 및 `형식의 오류` 
    이와 같은 경우에는 다음의 절차를 따라서 진행 
   > - [ ]  [길벗](https://www.gilbut.co.kr) 홈페이지에 접속 
   > - [ ]  고객센터 클릭 
   > - [ ]  1:1문의 접속 후에 오류 및 문의 사항을 제보 

위의 사항 외에 `이슈`라면 가능한 빨리(평균적으로 1일 이내) 회신드리도록 하겠습니다. 

## [ 내용 ]
삭제

**Comment by sysnet4admin** [comment]
....? 어떤 삭제인지 모르지만... 아침에 돌려본 결과 문제가 없습니다. 
또한 현재 케이스는 #36 에서 진행 중이니 해당 내용을 참고하시기 바랍니다.
