### ISSUE TITLE
[ 4.3.1 / p245 ] sed 명령어를 통한 Dockerfile 내용 수정

### ISSUE THREAD

**Issue by bangjaeyoung** [sysnet4admin/_Book_k8sInfra#38]
## [ 내용 ]
**mac os**를 사용하고 있습니다.

해당 페이지 9번에서 Dockerfile의 내용을 수정하는 `sed` 명령어가 동작하지 않습니다.

다음과 같은 내용 수정 명령어를 통해 정상 동작하는 것을 확인했습니다.
`sed -i '' 's/Application/Development/' Dockerfile`

책에 표기된 `sed` 명령어가 잘 동작하지 않으실 경우,
위 명령어를 통해 Dockerfile 내용 수정 가능할 것으로 판단됩니다. 참고 부탁드립니다.

**Comment by sysnet4admin** [comment]
ch4에서 Dockerfile을 수정할 때는 센트OS에서 진행하고 있습니다. 
Mac OS에서 안된다는 뜻이 무슨 뜻이신지 모르겠는데요. 

책과 관련이 없이 **다른 운영체제에서 sed 사용 방법**을 적으신 것인지 안내를 부탁드립니다.

**Comment by bangjaeyoung** [comment]
네 맞습니다! 말씀 주신대로, 책 내용 오류에 대한 이슈는 아닙니다.
4장 Dokcer 챕터는 Mac OS에서 실습해도 될 것 같아 진행하던 도중,
책을 따라하시는 다른 독자분들이 참고하실 수 있도록 말씀드린 것입니다!
