### ISSUE TITLE
[ 챕터 위치 / 페이지 ] box - yum 이슈

### ISSUE THREAD

**Issue by sseregit** [sysnet4admin/_Book_k8sInfra#39]
**중요**  이슈를 받기 어려운 사항은 다음과 같습니다. 

1. 책에 사용되는 환경 및 기술과 관련된 `질문` </br>
   또는 책에서 구성한 `환경외` 조건에서 발생한 이슈
   > `goto` 
   > 1. 쿠버네티스 오픈 채팅: https://open.kakao.com/o/gxSooElb (암호: kubectl)
   > 2. 쿠버네티스 유저 그룹: https://www.facebook.com/groups/k8skr
   
2. 개개인의 환경에 영향을 받는 `vagrant` 에러(error)와 관련된 이슈 </br>
   하지만 다음의 사항에 모두 해당 한다면 이슈를 부탁드립니다.  
   > - [ ]  초기화된(새로 설치) 노트북(또는 PC)
   > - [ ]  책에서 제시한 프로그램과 동일한 버전 설치
   > - [ ]  할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행
   > - [ ]  2대 이상 동일하게  문제가 발생함

3. 책의 `오타` 및 `형식의 오류` 
    이와 같은 경우에는 다음의 절차를 따라서 진행 
   > - [ ]  [길벗](https://www.gilbut.co.kr) 홈페이지에 접속 
   > - [ ]  고객센터 클릭 
   > - [ ]  1:1문의 접속 후에 오류 및 문의 사항을 제보 

위의 사항 외에 `이슈`라면 가능한 빨리(평균적으로 1일 이내) 회신드리도록 하겠습니다. 

## [ 내용 ]
"Could not resolve host: mirrorlist.centos.org; Unknown error"

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64

2024-9-20에 책을 읽으면서 안내에 따라 vagrant 설정을하고 "sysnet4admin/CentOS-k8s" vagrant cloud에 있는 box를 이용하면 위와 같은 yum 관련 error가 나고 있습니다.
box의 수정이 필요해 보입니다.

**Comment by sysnet4admin** [comment]
이미 이슈 #36 그리고 #37 에서 진행하고 수정한 내용입니다. 
이슈를 열기 전에 종료된 이슈를 살펴보시고 해당 문제로 해결되지 않을 경우 이슈를 열어주시기 바랍니다.

**Comment by sseregit** [comment]
제가 겪은 문제는 chapter2에서 겪은 문제이고 제가 챕터 위치를 안적었네요. 

2.2.3에 해당 오류로 가상머신 추가되지 않아 이슈로 올리는게 좋아 보여 올렸고

챕터3부터는 깃헙위치를 안내 해주시는 부분이 있어 문제 없이 현재 진행중입니다.

**Comment by sysnet4admin** [comment]
@sseregit 님 말씀해 주신 부분은 적용하고 테스트도 진행해서 해결됨을 확인했습니다.

https://github.com/sysnet4admin/_Book_k8sInfra/blob/a8530c6884aebde43a1de36b384585efd2b0d691/ch2/2.2.2/install_pkg.sh#L3-L7

https://github.com/sysnet4admin/_Book_k8sInfra/blob/a8530c6884aebde43a1de36b384585efd2b0d691/ch2/2.2.3/install_pkg.sh#L3-L7

해당 내용을 알려주셔서 감사합니다.
가능하시다면 다음에는 혼동이 없도록 템플릿 내용을 채워서 주시면 좀 더 혼동을 줄일 수 있을 것 같습니다.

**Comment by sysnet4admin** [comment]
위의 내용은 1주일 간 모니터링 후에 클로즈 됩니다.

**Comment by sysnet4admin** [comment]
nothing more response.
