### ISSUE TITLE
[ ch5 / p434] Freesytle로 간단히 echo-ip 배포 -> docker: command not found 에러 발생

### ISSUE THREAD

**Issue by JAVANOM** [sysnet4admin/_Book_k8sInfra#40]
오류 내용 
git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
git config remote.origin.url https://github.com/Iac-source/echo-ip # timeout=10
Fetching upstream changes from https://github.com/Iac-source/echo-ip
git --version # timeout=10
git --version # 'git version 1.8.3.1'
git fetch --tags --progress https://github.com/Iac-source/echo-ip +refs/heads/:refs/remotes/origin/ # timeout=10
git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision 5ed2bf9132d6fabf9481ea8f90b1bdddd74490fe (refs/remotes/origin/main)
git config core.sparsecheckout # timeout=10
git checkout -f 5ed2bf9132d6fabf9481ea8f90b1bdddd74490fe # timeout=10
Commit message: "Update README.md"
First time build. Skipping changelog.
[workspace] $ /bin/sh -xe /tmp/jenkins4161428590763258365.sh

docker build -t 192.168.10.10:8443/echo-ip . /tmp/jenkins4161428590763258365.sh: line 2: **docker: command not found** Build step 'Execute shell' marked build as failure Finished: FAILURE

- jenkins pod 확인 결과 docker 설치가 안되어 있음
: volume mount는 책이랑 동일 하게 설정

- 책으로 동일하게 진행(ip만 다름)

**Comment by sysnet4admin** [comment]
안녕하세요 
해당 부분을 다시 확인해도 재현되지 않습니다. 
```
dpy-fs-dir-prod] $ /bin/sh -xe /tmp/jenkins2730457956399478124.sh
+ docker build -t [192.168.1.10:8443/echo-ip](http://192.168.1.10:8443/echo-ip) .
Sending build context to Docker daemon  174.1kB

Step 1/6 : FROM nginx:stable
stable: Pulling from library/nginx
a480a496ba95: Pulling fs layer
f7e45c747637: Pulling fs layer
692a61bd1d67: Pulling fs layer
8992a25329a6: Pulling fs layer
eec32f85414d: Pulling fs layer
f8eff2f530ec: Pulling fs layer
7a37000823d1: Pulling fs layer
8992a25329a6: Waiting
eec32f85414d: Waiting
f8eff2f530ec: Waiting
7a37000823d1: Waiting
[생략]
```
제 예상에는 #32 와 같이 일정 부분을 건너뛰셨거나, 호스트/가상 머신이 무언가가 다른 상태인 것 같습니다. 
재현이 될 수 있게 전제 재현 단계를 공유해 주시면 다시 확인해 보겠습니다.

**Comment by sysnet4admin** [comment]
+ 이슈를 올리는 템플릿에 맞게 올려주시기 바랍니다. 
+ 현재 이슈의 목적은 `안된다`를 올리는 목적으로 사용되지 않습니다.

**Comment by sysnet4admin** [comment]
이슈 조건에 맞지 않아 현재 케이스는 종료됩니다. 
필요시 추후에 내용을 다시 채워서 이슈를 열어주시기를 부탁드립니다.
