### ISSUE TITLE
vagrant up 시  VM 부팅중에 오류

### ISSUE THREAD

**Issue by leejinlee-kr** [sysnet4admin/_Book_k8sInfra#8]
2.1.3 베이그런트 구성하고 테스트하기 챕터에서 vagrant up 실행 도중 문제가 발생하였습니다.

![vagrant_up](https://user-images.githubusercontent.com/63401132/126478685-8f53b0db-03c9-43f4-9fda-b5d72a5618de.PNG)

환경은
vagrant 2.2.17
virtualbox 6.1.24
windows 10 64bits
이렇습니다.

vm부팅중에 오류가 나는데 어떻게 이 문제를 해결할 수 있을까요?

**Comment by leejinlee-kr** [comment]
virtualbox error log는 다음과 같습니다.

![virtualbox_error](https://user-images.githubusercontent.com/63401132/126487369-66d445d0-bd9a-4c0f-9629-0fb6658c6581.PNG)

**Comment by sysnet4admin** [comment]
'새 그룹' (한글)이 의심되긴 하는데 알 수 없습니다. 
`vagrant` 설치 후에 초기 구동(`init`) 부분은 개개인의 환경에 환경을 너무 많이 받기 때문에 이슈로 받기 어렵습니다. 
계속 내용을 보고 제가 찾아보고 질문해가면, 해결을 할 수 있기는 하겠지만 그것은 Repo's issue page에 맞지 않는 것 같습니다.
