### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by g9736ms** [sysnet4admin/_Book_k8sInfra#9]
**중요**  개개인의 환경에 영향을 받는 `vagrant` 에러(error)와 관련된 이슈는 받지 않습니다. 하지만 다음의 경우에는 가능합니다. 
 - 초기화된(새로 설치) 노트북(또는 PC)
 - 책에서 제시한 프로그램과 동일한 버전 설치
 - 할리스(IP가 겹침)를 제외한 카페 또는 집에서 실행
 - 2대 이상 동일하게  문제가 발생함 

## [ 챕터 위치 / 페이지 ]
285페이지에 헬름 설명 부분 들여쓰기가 되어 있는데 이게 의도 한 것인지 궁금합니다!

## [ 내용 ]
개연성으로 봤을 땐 큐브시티엘 커스터마이즈 헬름 순서대로 설명하는거 같은데
 헬름이 커스터마이즈에 들여쓰기 되어 있어서 커스터마이즈 안에 헬름이 포함 된 느낌?이라
이게 맞는지 궁금합니다

**Comment by sysnet4admin** [comment]
네 해당 부분을 출판사에 전달드렸고, 추후 발간 예정인 **쇄** 에서 적용한다고 하십니다. 감사합니다.
